// <auto-generated />
using System;
using DmitrievaOilMonitoringApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DmitrievaOilMonitoringApi.Migrations
{
    [DbContext(typeof(OilMonitoringApiContext))]
    [Migration("20260403124234_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DmitrievaOilMonitoringApi.Models.Oil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FlashPointC")
                        .HasColumnType("double precision");

                    b.Property<double>("ImpuritiesPct")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OperatingHours")
                        .HasColumnType("double precision");

                    b.Property<int>("StartStopCycles")
                        .HasColumnType("integer");

                    b.Property<double>("TAN")
                        .HasColumnType("double precision");

                    b.Property<double>("Viscosity")
                        .HasColumnType("double precision");

                    b.Property<double>("WaterContent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Oils");
                });

            modelBuilder.Entity("DmitrievaOilMonitoringApi.Models.OilConditionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("FlashPointC")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasLeak")
                        .HasColumnType("boolean");

                    b.Property<double>("ImpuritiesPct")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsTopup")
                        .HasColumnType("boolean");

                    b.Property<double>("MeanBearingTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("MeanOilTemp")
                        .HasColumnType("double precision");

                    b.Property<double>("MeanVibration")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OperatingHours")
                        .HasColumnType("double precision");

                    b.Property<int>("PumpId")
                        .HasColumnType("integer");

                    b.Property<double>("TAN")
                        .HasColumnType("double precision");

                    b.Property<double>("WaterContentPct")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PumpId");

                    b.ToTable("OilConditionRecords");
                });

            modelBuilder.Entity("DmitrievaOilMonitoringApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Иван Лаборантов",
                            Login = "laborant",
                            PasswordHash = "$2a$11$3ufDM9/ALD4/aoVANHk7FuFfFlJPcw8LfzQRlX7e8KQVIR3XfWoYi",
                            Role = "Laborant"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Петр Инженеров",
                            Login = "engineer",
                            PasswordHash = "$2a$11$3ufDM9/ALD4/aoVANHk7FuFfFlJPcw8LfzQRlX7e8KQVIR3XfWoYi",
                            Role = "Engineer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Мария Технологова",
                            Login = "technologist",
                            PasswordHash = "$2a$11$3ufDM9/ALD4/aoVANHk7FuFfFlJPcw8LfzQRlX7e8KQVIR3XfWoYi",
                            Role = "Technologist"
                        });
                });

            modelBuilder.Entity("DmitrievaOilMonitoringApi.Models.Pump", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int?>("OilId")
                        .HasColumnType("integer");

                    b.Property<double>("OilLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("OilPressure")
                        .HasColumnType("double precision");

                    b.Property<double>("OilTemperature")
                        .HasColumnType("double precision");

                    b.Property<double>("Power")
                        .HasColumnType("double precision");

                    b.Property<double>("PressureIn")
                        .HasColumnType("double precision");

                    b.Property<double>("PressureOut")
                        .HasColumnType("double precision");

                    b.Property<double>("ShaftRotationFrequency")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureBearing")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperatureBody")
                        .HasColumnType("double precision");

                    b.Property<double>("Vibration")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OilId")
                        .IsUnique();

                    b.ToTable("Pumps");
                });

            modelBuilder.Entity("DmitrievaOilMonitoringApi.Models.OilConditionRecord", b =>
                {
                    b.HasOne("DmitrievaOilMonitoringApi.Models.Pump", null)
                        .WithMany()
                        .HasForeignKey("PumpId")
                        .IsRequired();
                });

            modelBuilder.Entity("DmitrievaOilMonitoringApi.Models.Pump", b =>
                {
                    b.HasOne("DmitrievaOilMonitoringApi.Models.Oil", "Oil")
                        .WithOne()
                        .HasForeignKey("DmitrievaOilMonitoringApi.Models.Pump", "OilId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Oil");
                });
#pragma warning restore 612, 618
        }
    }
}
